### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by conceptofmind** [kyleliang919/Long-context-transformers#1]
Hello,

Thank you for the great work. I had worked on a similar Triton wrapper previously but have been looking for a wrapper that utilizes the original CUDA implementation. 

Is there a preferred method to cite you and this repository?

Thank you,

Enrico

**Comment by kyleliang919** [comment]
Thanks for your kind words! I added the citation options in the repo:
@software{Liang_Long_Context_Transformer_2023,
author = {Liang, Kaizhao},
doi = {10.5281/zenodo.7651809},
month = {2},
title = {{Long Context Transformer v0.0.1}},
url = {https://github.com/github/linguist},
version = {0.0.1},
year = {2023}
}

please also make sure to cite the amazing flash-attention, without it this repo will not be possible.
@article{dao2022flashattention,
  title={Flashattention: Fast and memory-efficient exact attention with io-awareness},
  author={Dao, Tri and Fu, Daniel Y and Ermon, Stefano and Rudra, Atri and R{\'e}, Christopher},
  journal={arXiv preprint arXiv:2205.14135},
  year={2022}
}

**Comment by conceptofmind** [comment]
I will be sure to cite both. 

The work done by Tri Dao is admirable. I have been using Flash Attention to train a few different models.

Thank you again,

Enrico
